name: Test clean install

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  test-install-direct:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
      if: runner.os == 'macOS'
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install base wheel
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install astromodels

    - name: Install 3ML
      run: |
        python setup.py install
  test-install-pip:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: [3.9]

    runs-on: ${{ matrix.os }}
    steps:
    - name: XCode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest
      if: runner.os == 'macOS'
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install base wheel
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install astromodels

    - name: Install 3ML
      run: |
        pip install threeML
